### ISSUE TITLE
Google Summer of Code 2023

### ISSUE THREAD

**Issue by glaslos** [honeynet/ochi#26]
Ochi is participating as part of the [Honeynet project](https://www.honeynet.org/) in the [Google Summer of Code 2023 (GSoC)](https://summerofcode.withgoogle.com/). Ochi is looking for engaged and motivated students to join us during 12 weeks of exciting collaboration. This is a very new project so there is a lot of potential to work on the foundation of it. 

Ochi is a web interface for live Honeypot events to correlate, filter and annotate.
As part of the GSoC'23 we would like to add the ability to filter the events using a version of the Wireshark query syntax as a DSL. Queries should be persistent and the backend should calculate metrics how often a query is matched.

- https://github.com/glaslos/ochi/issues/4
- https://github.com/glaslos/ochi/issues/6
- https://github.com/glaslos/ochi/issues/8

Furthermore the backend should support perma-links to events so they can be shared:

- https://github.com/glaslos/ochi/issues/5

Primary skills required are HTML/CSS/JavaScript. Secondary would be Golang but this can also be covered by the mentor of the project.

**Comment by aditygrg2** [comment]
I want to help and contribute to Ochi for this year's GSOC. Please guide me in understanding the requirements better and tips to make a strong proposal.

**Comment by ashutosh887** [comment]
Let me try this issue @glaslos

**Comment by glaslos** [comment]
Completed: https://www.honeynet.org/2023/08/24/gsoc-2023-project-summary-ochi/
