### ISSUE TITLE
Consider optimizing chevrotain DSL parsing logic on input change

### ISSUE THREAD

**Issue by dkumiszhan** [honeynet/ochi#49]
Currently we parse the event filter using chevrotain DSL definition when user types. When user clicks `Apply`, we parse the same filter again. We can do some optimization by persisting the result of filter parsing on input change and reusing it on pressing `Apply` button. Things to consider here is that persisted event might be out of date or invalid.

**Comment by glaslos** [comment]
Obsolete due to a misunderstanding on my side.
