### ISSUE TITLE
Add GitHub Action to run generate-check

### ISSUE THREAD

**Issue by glaslos** [honeynet/ochi#50]
We should stop Action if generate-check produces a different file. 
Developers should always re-generate changes and check in all changes.

**Comment by dkumiszhan** [comment]
I think I misunderstood it during the call. I think I did it here https://github.com/honeynet/ochi/blob/d46939cfc5d16a22e4c796ab6bec10450f4abe53/.github/workflows/svelte.yml#L24-L25

**Comment by glaslos** [comment]
Ah yes, I looked in the wrong file! But we should move it a bit up, no need to do anything else if it fails
