### ISSUE TITLE
Persist Queries 

### ISSUE THREAD

**Issue by glaslos** [honeynet/ochi#6]
Outcome: User can save and load their queries.

Metadata:
- Boolean if rules is active
- The actual query as DSL
- Description of the query

Flow:
- If the user is signed in and has an account:
- A save button added to the query input
- Save button opens a dialog asking for a name for the query, confirm saves the query 
- Create a new page with a list of all saved queries
- From the query page, queries can be loaded and applied to future events

This issue depends on #4

**Comment by dkumiszhan** [comment]
Hi @glaslos, I am working on setting up routing and I got a question. There are [several options](https://svelte.dev/docs/faq#is-there-a-router) how I can do that . I am leaning towards Routing from sveltekit. If I use that, I think I will need to switch from rollup to vite. Another approach is I can attempt to use [svelte-routing](https://www.npmjs.com/package/svelte-routing) or one of the other libraries with a rollup. Do you have a preferred approach?

**Comment by glaslos** [comment]
Wouldn't you need to run the sveltekit backend if you want to use its routing?

**Comment by dkumiszhan** [comment]
Oh, I didn't realise that. I read [this discussion](https://www.reddit.com/r/sveltejs/comments/p6c1i3/sveltekit_or_routify_or_neither/), and it seems to be possible to use sveltekit with custom backend but it is not so straightforward. I think I will look for a client-side routing library, but if you have something specific in mind, I will be happy to go with that.

**Comment by glaslos** [comment]
Nothing specific :) Client side routing sounds great
